version: 2.1

##--------Command to download Artifacts with optional paramters-----------##
commands:
  get-artifacts:
    parameters:
      description:
        type: string
      circleci-token:
        type: string
        default: $API_TOKEN
      repo-name:
        type: string
      branch-name:
        type: string
        default: $CIRCLE_BRANCH
    description: <<parameters.description>>

    steps:
      - run:
          name: Get Artifacts
          command: |
          
            # Install jq for json parsing
            sudo apt-get update
            sudo apt-get install jq

            # Set your CircleCI API token
            CIRCLECI_TOKEN=<<parameters.circleci-token>>

            # Set the repository and branch
            REPO_NAME=<<parameters.repo-name>>
            BRANCH=<<parameters.branch-name>>

            # Make the API request to get the pipelines of the repository
            PIPELINES=$(
            curl --location --request GET "https://circleci.com/api/v2/project/github/${CIRCLE_USERNAME}/${REPO_NAME}/pipeline?branch=${BRANCH}&filter=completed" \
             --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
            ) 

            echo "pipeline response is $PIPELINES"
            PIPELINE_ID=$(echo "$PIPELINES" | jq -r '.items[0].id')
            PIPELINE_NUMBER=$(echo "$PIPELINES" | jq -r '.items[0].number')
            echo "pipeline id is $PIPELINE_ID"
            echo "pipeline id is $PIPELINE_NUMBER"

            # Make the API request to get Workflow using Pipeline ID
            WORKFLOWS=$( 
            curl --location --request GET "https://circleci.com/api/v2/pipeline/${PIPELINE_ID}/workflow?branch=${BRANCH}&filter=completed" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )
            echo "workflow response is $WORKFLOW"
            WORKFLOW_ID=$(echo "$WORKFLOWS" | jq -r '.items[0].id')  
            WORKFLOW_NAME=$(echo "$WORKFLOWS" | jq -r '.items[0].name')
            PIPELINE_NUMBER=$(echo "$WORKFLOWS" | jq -r '.items[0].pipeline_number')
            WORKFLOW_STATUS=$(echo "$WORKFLOWS" | jq -r '.items[0].status')    
            echo "workflow id is $WORKFLOW_ID"
            echo "workflow name is $WORKFLOW_NAME"
            echo "workflow number is $WORKFLOW_NUMBER"
            echo "workflow status is $WORKFLOW_STATUS"
            echo "second pipeline number is $PIPELINE_NUMBER"
            
            # Make the API request to get Jobs from workflows
            JOBS=$( 
            curl --location --request GET "https://circleci.com/api/v2/workflow/${WORKFLOW_ID}/job?branch=${BRANCH}&filter=completed" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )

            echo "job response is $JOBS"
            JOB_ID=$(echo "$JOBS" | jq -r '.items[0].id')  
            JOB_NAME=$(echo "$JOBS" | jq -r '.items[0].name')
            JOB_NUMBER=$(echo "$JOBS" | jq -r '.items[0].job_number')
            JOB_STATUS=$(echo "$JOBS" | jq -r '.items[0].status')
            JOB_TYPE=$(echo "$JOBS" | jq -r '.items[0].type')
            PROJECT_SLUG=$(echo "$JOBS" | jq -r '.items[0].project_slug')        
            echo "job id is $JOB_ID"
            echo "job name is $JOB_NAME"
            echo "job number is $JOB_NUMBER"
            echo "job status is $JOB_STATUS"
            echo "project slug is $PROJECT_SLUG"

            # Make the API request to get the artifacts from job
            ARTIFACTS=$( 
            curl --location --request GET "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/$REPO_NAME/$JOB_NUMBER/artifacts" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )
            ARTIFACT_PATHS=$(echo "$ARTIFACTS" | jq -r '.items[].path')  
            ARTIFACT_URLS=$(echo "$ARTIFACTS" | jq -r '.items[].url')
       
            echo "artifact path is $ARTIFACT_PATHS"
            echo "artifact url is $ARTIFACT_URLS"

            # Download artifacts
            for artifact_url in $ARTIFACT_URLS; do
              # Split the given string and extract only the string after the last forward slash ("/") and use as a filename to save
              filename=$(basename $artifact_url)
              curl -sSL -o $filename $artifact_url
            done
  push-appdesigner-files-to-device:
    description: Clone and push the necessary ODK-X App Designer files to the emulator prior to testing Tables
    steps:
      - run:
          name: clone app designer repository to environemt
          command: |
            git clone -b "$CIRCLE_BRANCH" "https://github.com/$GITHUB_ACTOR/app-designer.git"
            ls -d */
            cd -designer/
            ls -d */
           # echo "git clone -b "$CIRCLE_BRANCH" "https://$GITHUB_TOKEN@github.com/$GITHUB_ACTOR/app-designer.git""
      - node/install
      - run:
          name: Run node --version & npm --version
          command: |
            node --version
            npm --version
      - run:
          name: Install grunt
          command: |
            npm install -g grunt-cli
            grunt --version
            npm install grunt --save-dev
      - run:
          name: Push Files to Emulator
          command: grunt pushadb
                    
orbs:
  android: circleci/android@2.3.0
  node: circleci/node@5.1.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Tables app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - run:
          name: Update Package list
          command: sudo apt-get update
      # - run:
      #     name: Install the latest Android SDK
      #     command: |
      #       sdkmanager --update
      - get-artifacts:
          description: Get artifacts from the 'Services' repository
          circleci-token: $API_TOKEN
          repo-name: 'services'
          branch-name: $CIRCLE_BRANCH

      - get-artifacts:
          description: Get artifacts from the 'Survey' repository
          circleci-token: $API_TOKEN
          repo-name: 'survey'
          branch-name: $CIRCLE_BRANCH
      
      # Runs command to push the ODK-X App Designer files to the emulator
      - push-appdesigner-files-to-device

      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew assemble
      
      # Install Dependncies to emulator
      - run:
          name: Install 'Services' app from downloaded artifacts to emulator
          command: |

            # Install Services App on emulator, Will use the `services_app-snapshot-basic-debug.apk` artifact downloaded from the get artifact jobs
            adb install services_app-snapshot-basic-debug.apk
            adb shell pm list packages
            # Install Services app to emulator
      - run:
          name: Install 'Survey' app from downloaded artifacts to emulator
          command: |

            # Install Survey App on emulator, Will use the `survey_app-snapshot-basic-debug.apk` artifact downloaded from the get artifact jobs
            adb install survey_app-snapshot-basic-debug.apk
            adb shell pm list packages



      - android/run-tests:
          test-command: ./gradlew test

      - android/run-tests:
          test-command: ./gradlew connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Echo Java home
          command: |
            echo $JAVA_HOME  

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Services
          command: ./gradlew assemble


workflows:
  build-test-deploy-workflow:
    jobs:
      - test
      # - build
      # - test:
      #     requires:
      #       - build




