version: 2.1

##--------Command to download Artifacts with optional paramters-----------##
commands:
  get-artifacts:
    parameters:
      description:
        type: string
      circleci-token:
        type: string
        default: $API_TOKEN
      repo-name:
        type: string
      branch-name:
        type: string
        default: $CIRCLE_BRANCH
    description: <<parameters.description>>

    steps:
      - run:
          name: install jq
          command: |
            sudo apt-get update
            sudo apt-get install jq
      - run:
          name: Get Artifacts
          command: |
            # Set your CircleCI API token
            CIRCLECI_TOKEN=<<parameters.circleci-token>>

            # Set the repository and branch
            REPO_NAME=<<parameters.repo-name>>
            BRANCH=<<parameters.branch-name>>

            
            # Make the API request to get the pipelines of the repository

            PIPELINES=$(
            curl --location --request GET "https://circleci.com/api/v2/project/github/${CIRCLE_USERNAME}/${REPO_NAME}/pipeline?branch=${BRANCH}&filter=completed" \
             --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
            ) 
            echo "response pipelines is $PIPELINES"
            PIPELINE_ID=$(echo "$PIPELINES" | jq -r '.items[0].id')
            echo "pipeline id is $PIPELINE_ID"

            # Make the API request to get Workflow using Pipeline ID
            WORKFLOWs=$( 
            curl --location --request GET "https://circleci.com/api/v2/pipeline/${PIPELINE_ID}/workflow" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )
            WORKFLOW_ID=$(echo "$WORKFLOWs" | jq -r '.items[0].id')  
            WORKFLOW_NAME=$(echo "$WORKFLOWs" | jq -r '.items[0].name')
            PIPELINE_NUMBER=$(echo "$WORKFLOWs" | jq -r '.items[0].pipeline_number')
            WORKFLOW_STATUS=$(echo "$WORKFLOWs" | jq -r '.items[0].status')    
            echo "workflow id is $WORKFLOW_ID"
            echo "workflow name is $WORKFLOW_NAME"
            echo "workflow number is $WORKFLOW_NUMBER"
            echo "workflow status is $WORKFLOW_STATUS"
            
            # Make the API request to get Jobs from workflows
            JOBS=$( 
            curl --location --request GET "https://circleci.com/api/v2/workflow/${WORKFLOW_ID}/job" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )
            JOB_ID=$(echo "$JOBS" | jq -r '.items[0].id')  
            JOB_NAME=$(echo "$JOBS" | jq -r '.items[0].name')
            JOB_NUMBER=$(echo "$JOBS" | jq -r '.items[0].job_number')
            JOB_STATUS=$(echo "$JOBS" | jq -r '.items[0].status')
            JOB_TYPE=$(echo "$JOBS" | jq -r '.items[0].type')
            PROJECT_SLUG=$(echo "$JOBS" | jq -r '.items[0].project_slug')        
            echo "job id is $JOB_ID"
            echo "job name is $JOB_NAME"
            echo "job number is $JOB_NUMBER"
            echo "job status is $JOB_STATUS"
            echo "project slug is $PROJECT_SLUG"

            # Make the API request to get the artifacts from job
            ARTIFACTS=$( 
            curl --location --request GET "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/$REPO_NAME/$JOB_NUMBER/artifacts" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )
            ARTIFACT_PATHS=$(echo "$ARTIFACTS" | jq -r '.items[].path')  
            ARTIFACT_URLS=$(echo "$ARTIFACTS" | jq -r '.items[].url')
       
            echo "artifact path is $ARTIFACT_PATHS"
            echo "artifact url is $ARTIFACT_URLS"

            # Download artifacts
            for artifact in $ARTIFACT_URLS; do
              filename=$(basename $artifact)
              curl -sSL -o $filename $artifact
            done
orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Tables app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - run:
          name: Update Package list
          command: sudo apt-get update
      # - run:
      #     name: Install the latest Android SDK
      #     command: |
      #       sdkmanager --update
      - get-artifacts:
          description: Get artifacts from the 'Services' repository
          circleci-token: $API_TOKEN
          repo-name: 'services'
          branch-name: $CIRCLE_BRANCH

      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew assemble

      - run:
          name: Install necessary dependencies ie 'Services' app from downloaded artifacts
          command: |
            # Install Services App on emulator
            adb install services_app/build/outputs/apk/snapshotBasic/debug/services_app-snapshot-basic-debug.apk
            adb shell pm list packages

      - android/run-tests:
          test-command: ./gradlew test

      - android/run-tests:
          test-command: ./gradlew connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Echo Java home
          command: |
            echo $JAVA_HOME  

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Services
          command: ./gradlew assemble


workflows:
  build-test-deploy-workflow:
    jobs:
      - test
      # - build
      # - test:
      #     requires:
      #       - build




