version: 2.1

##--------Command to download Artifacts with optional paramters-----------##
commands:
  get-artifacts:
    parameters:
      description:
        type: string
      circleci-token:
        type: string
        default: $API_TOKEN
      repo-name:
        type: string
      branch-name:
        type: string
        default: $CIRCLE_BRANCH
    description: <<parameters.description>>

    steps:
      - run:
          name: install jq
          command: |
            sudo apt-get update
            sudo apt-get install jq
      - run:
          name: Get Artifacts
          command: |
            # Set your CircleCI API token
            CIRCLECI_TOKEN=<<parameters.circleci-token>>

            # Set the repository and branch
            REPO_NAME=<<parameters.repo-name>>
            BRANCH=<<parameters.branch-name>>

            # Make the API request to get the pipelines of the Services repository

            # response=$(curl -sSL -u ${CIRCLECI_TOKEN}: -X GET \
            # "https://circleci.com/api/v2/project/github/${CIRCLE_USERNAME}/${REPO_NAME}/pipeline?branch=${BRANCH}&filter=completed" | jq -r '.items[0].id')

            response=$(curl -sSL -u ${CIRCLECI_TOKEN}: -X GET \
            "https://circleci.com/api/v2/project/github/${CIRCLE_USERNAME}/${REPO_NAME}/pipeline?branch=${BRANCH}&filter=completed") 

            # echo "response is $response"

            
            # Parse response and get the latest pipeline id
            pipeline_id=$(echo "$response" | jq -r '.items[0].id')

            echo "pipeline id is $pipeline_id"
        

            # Make the API request to get the artifacts for the latest completed pipeline
            artifacts_reponse=$( curl --location --request GET "https://circleci.com/api/v2/pipeline/${pipeline_id}/artifact" \
              --header 'Content-Type: application/json' \
              -u "${CIRCLECI_TOKEN}:" \
              )

            echo "Artifacts response is $artifacts_reponse"
            
            #Parse the artifacts response to get the artifacts urls
            artifacts_url=$(echo "$artifacts_reponse" | jq -r '.items[].url')
            
            echo "Artifacts Urls are $artifacts_url"
            # curl -sSL -u ${CIRCLECI_TOKEN}: -X GET \
            #   "https://circleci.com/api/v2/pipeline/${pipeline_id}/artifacts" | jq -r '.items[].url'
            
            # Download artifacts
            for artifact in $artifacts_url; do
              filename=$(basename $artifact)
              curl -sSL -o $filename $artifact
            done
orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Tables app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1

    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - run:
          name: Update Package list
          command: sudo apt-get update
      # - run:
      #     name: Install the latest Android SDK
      #     command: |
      #       sdkmanager --update
      - get-artifacts:
          description: Get artifacts from the 'Services' repository
          circleci-token: $API_TOKEN
          repo-name: 'services'
          branch-name: $CIRCLE_BRANCH

      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew assemble

      - run:
          name: Install necessary dependencies ie 'Services' app from downloaded artifacts
          command: |
            # Install Services App on emulator
            adb install services_app/build/outputs/apk/snapshotBasic/debug/services_app-snapshot-basic-debug.apk
            adb shell pm list packages

      - android/run-tests:
          test-command: ./gradlew test

      - android/run-tests:
          test-command: ./gradlew connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout
      - run:
          name: Install OpenJDK 8
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
            java -version

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Echo Java home
          command: |
            echo $JAVA_HOME  

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Services
          command: ./gradlew assemble


workflows:
  build-test-deploy-workflow:
    jobs:
      - test
      # - build
      # - test:
      #     requires:
      #       - build




